<?php

namespace Proxies\__CG__\diretorioBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Empresa extends \diretorioBundle\Entity\Empresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'nombre', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'ubicacion', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'direcciones', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'telefonos', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'pizarras', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'extenciones');
        }

        return array('__isInitialized__', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'nombre', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'ubicacion', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'direcciones', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'telefonos', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'pizarras', '' . "\0" . 'diretorioBundle\\Entity\\Empresa' . "\0" . 'extenciones');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Empresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setUbicacion($ubicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUbicacion', array($ubicacion));

        return parent::setUbicacion($ubicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUbicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUbicacion', array());

        return parent::getUbicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function addDireccione(\diretorioBundle\Entity\Direccion $direccione)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDireccione', array($direccione));

        return parent::addDireccione($direccione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDireccione(\diretorioBundle\Entity\Direccion $direccione)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDireccione', array($direccione));

        return parent::removeDireccione($direccione);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirecciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirecciones', array());

        return parent::getDirecciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addTelefono(\diretorioBundle\Entity\Telefono $telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTelefono', array($telefono));

        return parent::addTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTelefono(\diretorioBundle\Entity\Telefono $telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTelefono', array($telefono));

        return parent::removeTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonos', array());

        return parent::getTelefonos();
    }

    /**
     * {@inheritDoc}
     */
    public function addPizarra(\diretorioBundle\Entity\Pizarra $pizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPizarra', array($pizarra));

        return parent::addPizarra($pizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function removePizarra(\diretorioBundle\Entity\Pizarra $pizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePizarra', array($pizarra));

        return parent::removePizarra($pizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function getPizarras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPizarras', array());

        return parent::getPizarras();
    }

    /**
     * {@inheritDoc}
     */
    public function addExtencione(\diretorioBundle\Entity\Extencion $extencione)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExtencione', array($extencione));

        return parent::addExtencione($extencione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExtencione(\diretorioBundle\Entity\Extencion $extencione)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExtencione', array($extencione));

        return parent::removeExtencione($extencione);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtenciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtenciones', array());

        return parent::getExtenciones();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
