<?php

namespace diretorioBundle\Repository;

/**
 * ExtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtencionRepository extends \Doctrine\ORM\EntityRepository
{
}
