<?php

namespace diretorioBundle\Repository;

/**
 * PizarraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizarraRepository extends \Doctrine\ORM\EntityRepository
{
}
